/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#e3f2fd',
          100: '#bbdefb',
          200: '#90caf9',
          300: '#64b5f6',
          400: '#42a5f5',
          500: '#2196f3',
          600: '#1e88e5',
          700: '#1976d2',
          800: '#1565c0',
          900: '#0d47a1',
        },
        // Light mode colors - Enhanced
        light: {
          bg: '#ffffff',
          'bg-secondary': '#f8fafc',
          'bg-tertiary': '#f1f5f9',
          'bg-card': '#ffffff',
          'bg-hover': '#f0f9ff',
          text: '#0f172a',
          'text-secondary': '#334155',
          'text-muted': '#64748b',
          'text-accent': '#1e40af',
          border: '#e2e8f0',
          'border-secondary': '#cbd5e1',
          'border-accent': '#3b82f6',
          accent: '#3b82f6',
          'accent-secondary': '#1d4ed8',
          'accent-light': '#60a5fa',
          'accent-bg': '#dbeafe',
          success: '#059669',
          'success-bg': '#d1fae5',
          warning: '#d97706',
          'warning-bg': '#fef3c7',
          error: '#dc2626',
          'error-bg': '#fee2e2',
          purple: '#7c3aed',
          'purple-bg': '#ede9fe',
          cyan: '#0891b2',
          'cyan-bg': '#cffafe',
          emerald: '#059669',
          'emerald-bg': '#d1fae5',
        },
        // Dark mode colors (original - unchanged)
        dark: {
          bg: '#0f172a',
          'bg-secondary': '#1e293b',
          'bg-tertiary': '#334155',
          text: '#f8fafc',
          'text-secondary': '#cbd5e1',
          'text-muted': '#94a3b8',
          border: '#475569',
          'border-secondary': '#64748b',
          accent: '#3b82f6',
          'accent-secondary': '#60a5fa',
          success: '#10b981',
          warning: '#f59e0b',
          error: '#ef4444',
        },
      },
    },
  },
  plugins: [],
}
